from typing import Protocol
from models.player import Player
from models.game_result import GameResult
from game.board import Board


class UserInterface(Protocol):
    def display_current_player(self, current_player: Player) -> None: ...  
    def display_score(board, white_tiles: int, black_tiles: int) -> None: ...
    def display_board(self, board: Board, legal_moves: dict[tuple[int, int], list[tuple[int, int]]]) -> None: ...
    def display_result(self, result: GameResult) -> None: ...
    