from typing import Protocol
from enums.player import Player
from enums.game_result import GameResult
from models.board import Board


class UserInterface(Protocol):
    def run(self) -> None: ...
    def display_current_player(self, current_player: Player) -> None: ...  
    def display_score(self, white_tiles: int, black_tiles: int) -> None: ...
    def display_board(self, board: Board, legal_moves: dict[tuple[int, int], list[tuple[int, int]]]) -> None: ...
    def display_result(self, result: GameResult) -> None: ...
    